### ISSUE TITLE
cap architecture section - notes

### ISSUE THREAD

**Issue by andreas-kupries** [SUSE/doc-cap#208]
Ref https://trello.com/c/nG21xQlV/845-review-expanded-cap-architecture-section

Ref http://docserv.nue.suse.com/documents/CAP_1/cap-deployment/html/cha.cap.about.html#sec.cap.components

`.. the cf CLI, Stratos Web interface ...`

cf is a cli app like helm and kubectl, and should IMHO be marked the same as these (bold+underlined in the style shown)

Ref http://docserv.nue.suse.com/documents/CAP_1/cap-deployment/html/cha.cap.about.html#sec.cap.service-diagram

Maybe swap kubectl/helm and the Kube/Tiller boxes - This should remove the crossing of lines between kubectl/Kube and helm/Tiller.

Note, the arrows on the right saide of the uaa box look weird. One arrow seems to be vertical, but there is no line.

Moving the UAA box up to be between the two CAP boxes might detangle some more line crossings as well.

**Comment by cjschroder** [comment]
Thanks, those are good suggestions. cf CLI is the name of the client, so it does not get special formatting. I didn't move the UAA box even though it should be moved because it is a lot of work to move all those lines when I don't have the source file.

Closing for https://github.com/SUSE/doc-cap/pull/214
