### ISSUE TITLE
clean up formatting, tags, and entities

### ISSUE THREAD

**Issue by cjschroder** [SUSE/doc-cap#262]
Doubtless there are formatting and tagging errors, and words that should be replaced with entities. This is a great issue for anyone who wants to contribute, and to sharpen their XML skills.

**Comment by cjschroder** [comment]
Also look where procedure tags should be applied, rather than paragraphs or sections.

**Comment by btat** [comment]
link labels are examples that still exist

**Comment by gaktive** [comment]
Seems like we've fixed a lot already here. Would we be repurposing sections for 2.0?

**Comment by btat** [comment]
> Seems like we've fixed a lot already here. Would we be repurposing sections for 2.0?

It's likely that some parts will be repurposed for 2.0 and we could do the cleanup, if needed, on the particular section at that time.

I think we've done a good job of using things correctly after this issue was created and Lukas (#619) and Claudia (#462) have since fixed many cases. I'd vote for closing this one and opening issues for specific cases as we come across them.

**Comment by gaktive** [comment]
Agreed, closing for now.
