### ISSUE TITLE
AKS Service Broker section variable names inconsistent from AKS chapter

### ISSUE THREAD

**Issue by PeterAnderssonSUSE** [SUSE/doc-cap#293]
7.9  Configuring and Testing the Native Microsoft AKS Service Broker

https://www.suse.com/documentation/cloud-application-platform-1/singlehtml/book_cap_guides/book_cap_guides.html#sec.cap.azure-service-broker

Please use same variables through the whole documentation
Earlier `$LOCATION` is `$REGION`

`$AZURE_SUBSCRIPTION_ID` is the same as `$SUBSCRIPTION_ID`

**Comment by cjschroder** [comment]
This is messy-- the Azure documentation lists regions where AKS is supported, e.g. Australia East, Canada Central (https://docs.microsoft.com/en-us/azure/aks/container-service-quotas). Which of course are not the literal regions to use in az commands:
```
az account list-locations
...
    "displayName": "Australia East",
    "id": "/subscriptions/foo/australiaeast",
```
But the `az` command doesn't provide a `region` option, but instead 'location`. (And they wonder why users complain how everything is confusing.) To save wearisome explanations how location and region are the same, I think it's better to stick with $REGION.

Also I think $SUBSCRIPTION_ID is preferable because  it is shorter than $AZURE_SUBSCRIPTION_ID.
