### ISSUE TITLE
Add example commands for nicer log output

### ISSUE THREAD

**Issue by cjschroder** [SUSE/doc-cap#321]
Provide some commands for searching and formatting logs in a more human-readable format
Logging output examples in https://github.com/SUSE/doc-cap/pull/320

See: https://www.suse.com/documentation/cloud-application-platform-1/singlehtml/book_cap_guides/book_cap_guides.html#sec.cap.log-levels

**Comment by btat** [comment]
The logging output examples in #320 are produced from SCF/CF and as far as I can tell, it doesn't seem like commands exist to format them.

As a workaround, added line breaks to the examples via #517  (using the pdf output as a reference) so that the output is more readable and not just a single line with (a lot of) horizontal scrolling.
