### ISSUE TITLE
recreate-pods may not be needed for upgrades now

### ISSUE THREAD

**Issue by btat** [SUSE/doc-cap#350]
https://trello.com/c/liEA7Hvc/956-2-confirm-recreate-pods-is-actually-required-for-upgrades

it was mentioned there's a pending decision about a race condition before deciding how to proceed with `--recreate-pods`

**Comment by gaktive** [comment]
We haven't seen the race condition so we've asked the submitter for more details. It's possible that they were upgrading from 1.2.1 directly to 1.3.1 which isn't a supported scenario.

We should confirm with PM but at this point, we should update the release notes at least since this will be a big help for current admins.

**Comment by btat** [comment]
See https://github.com/SUSE/cap-release-notes/pull/55
