### ISSUE TITLE
[doc] 8.3  Create Tiller Service Account

### ISSUE THREAD

**Issue by it-slav** [SUSE/doc-cap#368]
8.3  Create Tiller Service Account

https://www.suse.com/documentation/cloud-application-platform-1/singlehtml/book_cap_guides/book_cap_guides.html#sec.cap.tiller-service

I do not understand the order of this page.
In the middle it says "First create the configuration file...", should that be done before running the commands above?
And running the commands:
kubectl create -f rbac-config.yaml
helm init --service-account tiller
gives errormessages saying that things already exists. Is that expected?

**Comment by btat** [comment]
@it-slav that section is providing 2 different methods of creating a tiller service account as stated in the first sentence of the section: `There are two ways to create a service account: from the command line with kubectl, or applying a configuration file with kubectl and helm`. Your seeing the `already exists` message because you're trying to run both methods.

However, to avoid confusion the section has already been changed to only indicate 1 method via commit https://github.com/SUSE/doc-cap/commit/f9bdb610fc3527120065d7d7b7a871751227a7a7 (not published yet, but available on our staging server).
