### ISSUE TITLE
[doc] 12.1  Prerequisites - CaaSP v2 - seems this needs to be updated to CaaSP v4

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-cap#684]
12.1  Prerequisites

https://documentation.suse.com/suse-cap/1.5.1/single-html/cap-guides/#sec-cap-prereqs-openstack
------

--> SUSE-CaaS-Platform-2.0-KVM-and-Xen.x86_64-1.0.0-GM.qcow2,

**Comment by btat** [comment]
Thanks for bringing this up. After some discussion with the team, we've decided it'd make more sense to remove this chapter rather than updating it. The chapter talks about deploying CaaSP on Openstack and in the context of CAP it's a better inside the CaaSP chapter with links to the CaaSP documentation for detailed instructions.
