### ISSUE TITLE
Document HA option

### ISSUE THREAD

**Issue by fsundermeyer** [SUSE/doc-cap#70]
@cornelius reported in [bsc 1096212](https://bugzilla.suse.com/show_bug.cgi?id=1096212):

There is an option in the config now to enable HA defaults so that you don't have to set options for all services separately. It's `config.HA`. We should document this as it makes an HA setup as simple as it can get.

**Comment by cjschroder** [comment]
How is config.HA used? Are there any internal docs? It is not in the UAA or SCF values.yaml files.

**Comment by mook-as** [comment]
Interesting; we had that in there as a development shortcut to start the smallest HA configuration and didn't intend that to be used by customers (since they would probably want to customize things to suit their deployment scenarios).  I didn't know of a decision to change that status.

In case we _do_ want to actually document it: `config.HA` (previously known as `sizing.HA`), when set to true, will change any roles at the default size (of 1) to be a minimal HA deployment instead; for example, there will be multiple router instances.  The number of instances is listed in the comment in the helm values file (`helm inspect values suse/cf`); for example, `# For high availability it needs at least 2 instances.`

Note that we only check if the number of instances is at the default, not if you have set it; this means you can't explicitly set "HA but 1 router", because it just assumes that was the default and overrides it to 2 instances instead.

Please check with… somebody that we want this to be documented before writing all this down, of course :)

**Comment by cjschroder** [comment]
@mook-as I was looking for a literal config.HA option, not 
````
config:
  # Flag to activate high-availability mode
  HA: false
````

Think literal for us lowly end lusers :)

**Comment by mook-as** [comment]
But it's the same thing; the helm command line accepts things by joining the nesting levels with dots (`.`), as in `--set config.HA=true` to modify the option you quoted :)

**Comment by cjschroder** [comment]
Thanks! See if this works for you.
http://docserv.nue.suse.com/documents/CAP_1/cap-deployment/single-html/#sec.cap.ha-prod

**Comment by mook-as** [comment]
Hi! Sorry, I dropped this on the floor because Hack Week :D

Reviewing https://susedoc.github.io/doc-cap/develop/cap-deployment/html/cha.cap.install-production.html#sec.cap.ha-prod :
- There's no need to actually download the chart: `helm inspect values suse/uaa | perl -ne '/^sizing/..0 and do { print $.,":",$_ if /^  [a-z]/ || /high avail|scale|count/ }'` (a combination of the two commands we already have) works fine
- Passing `--set config.HA=true` works, but is more likely to be error-prone in the future (because when you need to upgrade or something you're likely to forget).  But that's generally true of using `--set`, whatever the situation.

**Comment by cjschroder** [comment]
Nice perl-fu, @mook-as. Thanks!

**Comment by cjschroder** [comment]
https://github.com/SUSE/doc-cap/commit/1451ecd473ae4ca66ce581724263f0364ffb3b7f
