### ISSUE TITLE
[doc] 6.1  Deploy Stratos on SUSE® CaaS Platform - v2.6.1 is outdated - need to be updated to 3.1.0

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-cap#804]
6.1  Deploy Stratos on SUSE® CaaS Platform

https://documentation.suse.com/suse-cap/1.5.1/single-html/cap-guides/#sec-cap-stratos-prod
-------
v2.6.1 is outdated - need to be updated to 3.1.0

and an explanation for the content of values.yaml is required.. it seems to be completely different from 2.6.1

**Comment by troytop** [comment]
Stratos 2.6.1 was the version available when CAP 1.5.1 was released, so we will keep this as is.

Anyone installing from the CAP 1.5.x stream should be installing the last patch release in the series (currently 1.5.2). Since Stratos 3.1.0 _has_ been validated with CAP 1.5.2, we will change the version number in https://github.com/SUSE/doc-cap/issues/805.
